version: "3"

services:
  solana-validator:
    image: dmitryr117/solana-noavx2:1.10.8
    #build: .
    container_name: solana-valitator
    restart: on-failure
    #command: "solana-test-validator"
    volumes:
      - ./validatorenv/test-ledger:/test-ledger
      - ./validatorenv/wallet:/wallet
      - ./validatorenv/locconfig.yml:/root/.config/solana/cli/config.yml
    ports:
      - 8899:8899
      #- "80:80/udp"
      #- "80:80/tcp"
     
  soldev:
    # IMPORTANT!: for local development make sure to turn on  
    image: dmitryr117/anchor-noavx2:0.24.2
    container_name: soldev
    restart: on-failure
    #command: "tail -f /dev/null"
    depends_on:
      - solana-validator
    volumes:
      - ./appdev:/sol
      - ./devenv/wallet:/wallet
      - ./devenv/config/localnet.yml:/root/.config/solana/cli/config.yml
    #ports:
    #   - 8899:8899
    #   - "80:80/udp"
    #   - "80:80/tcp"

    
