version: "3"

# ATTENTION!. Separate solana validator has issues when trying to upload programs.
# And so smart contracts have to be deployed withing localhost.
services:
  soldev:
    # IMPORTANT!: for local development make sure to turn on  
    image: dmitryr117/anchor-noavx2:0.24.2 # dmitryr117/anchor-noavx2:a0.24.2-s1.10.8-r1.56.0 
    container_name: soldev
    restart: on-failure
    working_dir: /
    # Later will need to add a sudo user a copy of my internal user
    command: /bin/bash /startup.sh
    # depends_on:
    #   - solana-validator
    volumes:
      - ./startup.sh:/startup.sh
      - ./appdev:/appdev
      - ./devenv/wallet:/wallet
      - ./devenv/config/validator.yml:/root/.config/solana/cli/config.yml
      - ./devenv/validator/test-ledger:/test-ledger
    environment:
      - NPM_LIVE_REGISTRY=registry.npmjs.org
      - NPM_LOCAL_REGISTRY=localhost:4873
      - PROGRAM_ROOT=/appdev/metaplex-program-library
    expose:
      - 8899
    # !IMPORTANT. Has to be on host net mode. Otherwise explorer.solana does not work.
    network_mode: "host"  

  verdaccio:
    image: verdaccio/verdaccio:5.10
    container_name: verdaccio
    restart: always
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - "4873:4873"
    volumes:
      - "./verdaccio/storage:/verdaccio/storage"
      - "./verdaccio/config:/verdaccio/conf"
      - "./verdaccio/plugins:/verdaccio/plugins"  

