storage: /verdaccio/storage
auth:
  htpasswd:
    file: /verdaccio/conf/.htpasswd
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
  yarnpkg:
    url: https://registry.yarnpkg.com/
packages:
  '@metaplex-foundation/*':
    access: $all
    publish: $all
  "@*/*":
    access: $all
    publish: $authenticated
    proxy: npmjs
  "**":
    proxy: npmjs
log: { type: stdout, format: pretty, level: http }
