FROM dmitryr117/solana:1.10.38-noavx2

ENV PATH="/root/.avm/bin:${PATH}"
ARG nodeversion="18.x"

RUN cargo install --git https://github.com/project-serum/anchor avm --locked --force && \
		avm install latest && \
		avm use latest && \
		anchor --version
		
RUN sh -c "$(curl -sSfL https://deb.nodesource.com/setup_${nodeversion})" && \
    apt-get update && \
    apt-get install -y git nodejs jq && \
    node --version && \
    npm install --global yarn ts-node

RUN npm install -g npm@latest

WORKDIR /appdev

CMD ["tail", "-f", "/dev/null"]
