FROM dmitryr117/rust:1.60.0

ARG solversion="v1.10.8"
ENV PATH="/root/.local/share/solana/install/active_release/bin:${PATH}"
ARG DEVNET_URL="https://api.devnet.solana.com"
# Separate run because solana version changes often
RUN sh -c "$(curl -sSfL https://release.solana.com/${solversion}/install)"

CMD ["tail", "-f", "/dev/null"]
